[versions]
agp = "8.10.1"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
wear = "1.3.0"
wearInput = "1.1.0"
coreKtxVersion = "1.16.0"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
wear = { module = "androidx.wear:wear", version.ref = "wear" }
wear-input = { module = "androidx.wear:wear-input", version.ref = "wearInput" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtxVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.1.21" }
android-library = { id = "com.android.library", version.ref = "agp" }

